### PR TITLE
Add options to enable fixed folder structure for received problems and contest

### LINKED ISSUE #28: CompetiTestReceive enhancements
I am so happy to see new features in this amazing NeoVim plugin. I found that `CompetiTestReceive` requires an argument and we can receive a problem or even a contest. But we need more work on this command.

I know that you are planning to add a custom template when a problem file is created and here are some features I really need.

### 1. Cancel fetching a contest or a problem

I was fetching a problem and wanted to exit the directory prompt by pressing <kbd>Esc</kbd> but it didn't work.

### 2. Default directory

We need more configuration to the custom directory for each online judge, I used to add problems in its own directory and inside its online judge directory. I saw some people also do this not only me. This is what my directories structure looks like:

```
├── <online judge>
    ├── <contest id>
        ├── <problem name>.cpp
    ├── <problem name>
            ├── main.cpp
```

### PR DESCRIPTION
**Pull request by xeluxee**
This should fix #28, #29 and #32

@ayham-1  @MuhammadSawalhy @vishalpaudel I need your feedback, please.

This PR adds 2 new options, `received_problems_directory` and `received_contests_directory`, they're both configured the same way:
- `false` to use flexible directories
- string with competitest modifiers: e.g. `$(HOME)/Competitive Programming/$(JUDGE)/$(CONTEST)/`
- function accepting three arguments: problem, group and url
``` lua
received_problems_directory = function(problem, group, url)
	local hyphen = string.find(group, " - ", 1, true)
	local judge, contest
	if not hyphen then
		judge = group
		contest = "unknown_contest"
	else
		judge = string.sub(group, 1, hyphen - 1)
		contest = string.sub(group, hyphen + 3)
	end

	return string.format("%s/some_folder%f/%s/%s/%d", vim.loop.os_homedir(), math.random(), judge, contest)
end
```

Available receive-modifiers:
| modifier | meaning |
| ---- | ---- |
| `$()`    | insert dollar |
| `$(HOME)`    | home directory                        |
| `$(PROBLEM)` | Problem name, `name` field            |
| `$(GROUP)`   | judge and contest name, `group` field |
| `$(JUDGE)`   | first part of `group`, before hyphen  |
| `$(CONTEST)` | second part of `group`, after hyphen  |
| `$(URL)`     | problem url, `url` field              |
| `$(MEMLIM)`  | available memory, `memoryLimit` field |
| `$(TIMELIM)` | time limit, `timeLimit` field         |

`$(DATE)` will be implemented later, along with #39

### CODE REVIEW

**Comment by MuhammadSawalhy** [comment]
I think when the `received_problems_directory` is set, there is no need to display a problem for the problem. And when the default language of the template is set, there is no need to prompt for the language.

When the problem is received and the file is created from the template, the created file should be automatically opened. This behaviour exists in the CPH VSCode plugin.

**Comment by MuhammadSawalhy** [comment]
> By default telescope maps `<C-c>` to close window

Ok <kbd>ESC</kbd> in NORMAL mode may not be a good idea, but what about consistency? Why <kbd>ctrl</kbd>+<kbd>q</kbd> is used to close the test cases editor and <kbd>ctrl</kbd>+<kbd>c</kbd> is used to close the problem directory prompt?

**Comment by xeluxee** [comment]
I've added 5 options:
- `received_files_extension`: defaults to `cpp`
- `received_problems_prompt_filename`: boolean, whether to prompt user for filename when receiving a single problem or not
- `received_contests_prompt_extension`: boolean, whether to prompt user for files extensions when receiving a contest or not
- `open_received_problems`: boolean, whether to automatically open received problems or not
- `open_received_contests`: boolean, whether to automatically open all problems of a received contests or not

**Comment by xeluxee** [comment]
> Why is ctrl+q used to close the test cases editor and ctrl+c is used to close the problem directory prompt?

`<C-c>` is the default close keymap in [nui input](https://github.com/MunifTanjim/nui.nvim/blob/main/lua/nui/input/README.md) popup. As already said, I'll make insert and normal mode mappings configurable.

**Comment by MuhammadSawalhy** [comment]
Great! :heart:

**Comment by MuhammadSawalhy** [comment]
In the case of Java the file name must match the class name, so is it better to **_configure the filename rather than the file directory_**? Should we **not care** about another option to configure the contests directory and treat each problem of the contest **as if it is fetched alone**?!

**Comment by xeluxee** [comment]
> I've just noticed this data received from CompetitiveCompanion, the java class name which must be the same. Can you make add some modifiers for the template?

I can add `$(JAVA_MAIN_CLASS)` and `$(JAVA_TASK_CLASS)` modifiers.

> In the case of Java the file name must match the class name, so is it better to configure the filename rather than the file directory? Should we not care about another option to configure the contests directory and treat each problem of the contest as if it is received alone?!

Yes, we can configure filename rather than directory for received problems. So we need `$(CWD)` and `$(FEXT)` modifiers.

> But I suggest instead of sending many arguments to the function, it can get the received problem from CompetitiveCompanion as a table in Lua, so the function can get any information possible about the problem.

Right.

**Comment by xeluxee** [comment]
> > In the case of Java the file name must match the class name, so is it better to configure the filename rather than the file directory? Should we not care about another option to configure the contests directory and treat each problem of the contest as if it is received alone?!
> 
> Yes, we can configure filename rather than directory for received problems. So we need `$(CWD)` and `$(FEXT)` modifiers. What about an option `received_problems_path`, that can be configured as follows:
> 
> - string: `$(HOME)/Competitive Programming/$(JUDGE)/$(CONTEST)/$(PROBLEM).$(FEXT)`
> 
> - function accepting task and file extension as arguments, returning absolute file path
> 
> 
> By default it's a string, `$(CWD)/$(PROBLEM).$(FEXT)`. Then I can rename `received_problems_prompt_filename` to `received_problems_prompt_path`, so users can decide whether to see prompt or not.

It's better to not do the same for contests, and use 4 options instead:
- `received_contests_directory`: root directory of received contest, can be string or function as `received_problems_path`. By default it's `$(CWD)`
- `received_contests_problems_path`: relative path from contest root directory, can be string or function, and this option can be configured to match different use-cases like
  - `$(PROBLEM).$(FEXT)`: default behavior, put all files in the same directory
  - `$(PROBLEM)/main.$(FEXT)`: every problem in a different directory
  - `$(PROBLEM)/$(JAVA_MAIN_CLASS).$(FEXT)`: for java, to make filename and classname equal
  - `$(JAVA_TASK_CLASS).$(FEXT)`: another way for java (but also for every language[^1]) with all files in the same directory
- `received_contests_prompt_directory`: whether to show a prompt or not to set contest root directory
- `received_contests_prompt_extension`: already implemented

A single option with full file path for contests is not prompt-friendly, since it would require users to see a prompt for each problem. This way users can see at most two prompts when receiving a contest, one for contest root directory and another one for file extension.

[^1]: the modifier `JAVA_TASK_CLASS` is generated from problem name removing all non-alphabetic or non-numeric characters, including spaces and punctuation. As competitive companion README states: "The classname-friendly version of the problem's full name. Cannot be the same as mainClass. Can also be useful for non-Java tools because a classname-friendly string is also a filename-friendly string"

**Comment by MuhammadSawalhy** [comment]
My preference for this is to make it simple and configure only the path of the received problem and when a user tries to receive a contest the plugin will create a file for each problem using `received_problems_path`. But if you see that we need a separate option to configure the path of the received contest, you can consider `received_contest_problem_path`.

The more options to configure the more complicated the plugin will be and the more bloated the README will be.

**Comment by MuhammadSawalhy** [comment]
> is necessary for users who prefer being asked for contest root directory with a prompt, otherwise they'd need to see a prompt for each received problem.

Great, You convinced me!

**Comment by xeluxee** [comment]
> I'm planning to introduce these options with this PR (some of them are already implemented): 
> - `received_files_extension`: string
> - `open_received_problems`: boolean
> - `open_received_contests`: boolean
> - `received_problems_path`: string or function
> - `received_problems_prompt_path`: boolean
> - `received_contests_directory`: string or function
> - `received_contests_problems_path`: string or function
> - `received_contests_prompt_directory`: boolean
> - `received_contests_prompt_extension`: boolean

@MuhammadSawalhy take a look at latest commit, I've implemented all the above options

**Comment by xeluxee** [comment]
I've just updated README, this PR is ready to be merged

**Pull request merged**
