### PR TITLE
flexible directories are now optional use

### PR DESCRIPTION
**Pull request by ayham-1**
Add option to use hard-coded directories when cloning contests/problems.

By default this feature is turned on.

### CODE REVIEW

**Comment by MuhammadSawalhy** [comment]
Great!
Waiting for this feature

**Comment by xeluxee** [comment]
I suggest the following changes:
- remove `use_flexible_directories` option
- `contests_directory` should accept one of the following values:
	- `false` to use flexible directories
	- string to specify contest directory
- add an option `problems_directory` for received problems, that is configured similarly to `contests_directory`

**Comment by xeluxee** [comment]
As @MuhammadSawalhy [pointed out](https://github.com/xeluxee/competitest.nvim/issues/28#issuecomment-1449022745), users could prefer functions to configure contest directory.

So both `contests_directory` and `problems_directory` should accept one of the following values:
- `false` to use flexible directories
- string to specify contest directory (with new _receive-modifiers_)
- function with one argument, a table with fields `problem`, `group`, `url`

I'd like to introduce a new set of modifiers, the receive-modifiers, that should be kept separated from file format modifiers and should be used to evaluate `contests_directory`, `problems_directory` and comments in template files (from #39):

| modifier | meaning |
| ---- | ---- |
| `$(PROBLEM)` | Problem name, `name` field            |
| `$(GROUP)`   | judge and contest name, `group` field |
| `$(JUDGE)`   | first part of `group`, before hyphen  |
| `$(CONTEST)` | second part of `group`, after hyphen  |
| `$(URL)`     | problem url, `url` field              |
| `$(MEMLIM)`  | available memory, `memoryLimit` field |
| `$(TIMELIM)` | time limit, `timeLimit` field         |
| `$(HOME)`    | home directory                        |
| `$(DATE)`    | current time, following `date_format` |

Note that `$(GROUP)`, `$(JUDGE)` and `$(CONTEST)` are different modifiers, but the latter two modifiers are generated from the former. Also `$(MEMLIM)`, `$(TIMELIM)` and `$(DATE)` are meant to be used in template files only.

Is these enough to reach an agreement on #28? @ayham-1 @MuhammadSawalhy

**Comment by MuhammadSawalhy** [comment]
Seams like I need to learn Lua and get a deep dive into this PR!

**Comment by xeluxee** [comment]
Closing with #40

**Pull request closed without merging**
